const powers = {
    // entries:
    "Mage+Human": "#012 - Lightning Flare",
    "Mage+Fey": "#009 - Frost Bolt",
    "Mage+Dwarf": "#019 - Spike Shield",
	"Mage+Halfling": "#008 - Alter Fate",
	"Mage+Small": "#005 - Flame Slash",
    "Mage+Big": "#017 - Shut Up",
    "Mage+Nimble": "#001 - Lightning Darts",
	"Mage+Stout": "#003 - Icy Breath",
	"Mage+Simple-minded": "#002 - Fireball",
    "Mage+Streetsmart": "#014 - Mirror Image",
    "Mage+Booksmart": "#015 - Lightning Bolt",
	"Mage+Wise": "#018 - Inner Peace",
	"Mage+Military": "#006 - Piercing Spiral",
    "Mage+Criminal": "#010 - Acid Splash",
    "Mage+Noble": "#004 - Cutting Words",
	"Mage+Craftsman": "#011 - Kinetic Blast",
	"Mage+Aggressive": "#013 - Reckless Blast",
    "Mage+Cautious": "#007 - Bubble Shield",
    "Mage+Honest": "#020 - Expose",
	"Mage+Dishonest": "#016 - Yours is Mine",
	"Fighter+Human": "#031 - Charge",
	"Fighter+Fey": "#025 - Flame Punch",
	"Fighter+Dwarf": "#032 - Weapon Toss",
	"Fighter+Halfling": "#039 - Roundhouse Kick",
	"Fighter+Small": "#030 - Hide in Plain Sight",
	"Fighter+Big": "#033 - Throw",
	"Fighter+Nimble": "#024 - Power Strike",
	"Fighter+Stout": "#035 - Stunning Palm",
	"Fighter+Simple-minded": "#023 - Shatter",
	"Fighter+Streetsmart": "#037 - Headbutt",
	"Fighter+Booksmart": "#029 - Words of Advice",
	"Fighter+Wise": "#026 - Well Prepared",
	"Fighter+Military": "#027 - In Formation",
	"Fighter+Criminal": "#028 - Thieves' Tool",
	"Fighter+Noble": "#040 - Frost Stomp",
	"Fighter+Craftsman": "#038 - Meat Grinder",
	"Fighter+Aggressive": "#022 - Furious Charge",
	"Fighter+Cautious": "#036 - Disarm",
	"Fighter+Honest": "#034 - Pummel",
	"Fighter+Dishonest": "#021 - Sucker Punch",
    "Ranger+Human": "#043 - Critical Hit",
	"Ranger+Fey": "#041 - Snipe",
	"Ranger+Dwarf": "#054 - Eagle Eye",
	"Ranger+Halfling": "#047 - Disable",
	"Ranger+Small": "#057 - Aimed Shot",
	"Ranger+Big": "#056 - Through and through",
	"Ranger+Nimble": "#050 - Quickshot",
	"Ranger+Stout": "#048 - Monster Hunt",
	"Ranger+Simple-minded": "#049 - Magebane Arrow",
	"Ranger+Streetsmart": "#053 - Flash Arrow",
	"Ranger+Booksmart": "#045 - Magical Arrows",
	"Ranger+Wise": "#052 - Charged Shot",
	"Ranger+Military": "#042 - Barrage",
	"Ranger+Criminal": "#051 - Arrow Stab",
	"Ranger+Noble": "#058 - Guiding Bolt",
	"Ranger+Craftsman": "#046 - Rain of Bolts",
	"Ranger+Aggressive": "#059 - One Shot, One Kill",
	"Ranger+Cautious": "#060 - Hobbling Shot",
	"Ranger+Honest": "#055 - Hunter's Mark",
	"Ranger+Dishonest": "#044 - Acid Arrow",
	"Human+Small": "#077 - Fade Away",
	"Human+Big": "#066 - Protective Rush",
	"Human+Nimble": "#090 - Shift",
	"Human+Stout": "#063 - Second Wind",
	"Human+Simple-minded": "#128 - Intuition",
	"Human+Streetsmart": "#128 - Intuition",
	"Human+Booksmart": "#098 - Concentrate",
	"Human+Wise": "#098 - Concentrate",
	"Human+Military": "#069 - Shield Up",
	"Human+Criminal": "#061 - Sleight of Hand",
	"Human+Noble": "#118 - Authority",
	"Human+Craftsman": "#129 - Tinkering",
	"Human+Aggressive": "#099 - Action Rush",
	"Human+Cautious": "#111 - Spike Armor",
	"Human+Honest": "#111 - Spike Armor",
	"Human+Dishonest": "#123 - Trickster",
	"Fey+Small": "#122 - Innocuous",
	"Fey+Big": "#064 - Stand Ground",
	"Fey+Nimble": "#085 - Blur",
	"Fey+Stout": "#063 - Second Wind",
	"Fey+Simple-minded": "#137 - Happy-Go-Lucky",
	"Fey+Streetsmart": "#137 - Happy-Go-Lucky",
	"Fey+Booksmart": "#076 - Mind Control",
	"Fey+Wise": "#136 - Wisdom of Age",
	"Fey+Military": "#094 - Inspire",
	"Fey+Criminal": "#082 - Sleep Powder",
	"Fey+Noble": "#094 - Inspire",
	"Fey+Craftsman": "#097 - Mindstorm",
	"Fey+Aggressive": "#115 - Bloodthirst",
	"Fey+Cautious": "#117 - Alert",
	"Fey+Honest": "#115 - Bloodthirst",
	"Fey+Dishonest": "#123 - Trickster",
	"Dwarf+Small": "#069 - Shield Up",
	"Dwarf+Big": "#121 - Iron Stomach",
	"Dwarf+Nimble": "#090 - Shift",
	"Dwarf+Stout": "#121 - Iron Stomach",
	"Dwarf+Simple-minded": "#081 - Tough Skin",
	"Dwarf+Streetsmart": "#116 - Storyteller",
	"Dwarf+Booksmart": "#074 - Silence",
	"Dwarf+Wise": "#136 - Wisdom of Age",
	"Dwarf+Military": "#064 - Stand Ground",
	"Dwarf+Criminal": "#093 - Maelstrom",
	"Dwarf+Noble": "#118 - Authority",
	"Dwarf+Craftsman": "#083 - Monster Manual",
	"Dwarf+Aggressive": "#132 - Short Temper",
	"Dwarf+Cautious": "#130 - Headstrong",
	"Dwarf+Honest": "#130 - Headstrong",
	"Dwarf+Dishonest": "#076 - Mind Control",
	"Halfling+Small": "#122 - Innocuous",
	"Halfling+Big": "#074	- Silence",
	"Halfling+Nimble": "#077 - Fade Away",
	"Halfling+Stout": "#078 - What doesn't kill you",
	"Halfling+Simple-minded": "#099 - Action Rush",
	"Halfling+Streetsmart": "#116 - Storyteller",
	"Halfling+Booksmart": "#083 - Monster Manual",
	"Halfling+Wise": "#097 - Mindstorm",
	"Halfling+Military": "#138 - Cunning Maneuver",
	"Halfling+Criminal": "#061 - Sleight of Hand",
	"Halfling+Noble": "#138 - Cunning Maneuver",
	"Halfling+Craftsman": "#129 - Tinkering",
	"Halfling+Aggressive": "#132 - Short Temper",
	"Halfling+Cautious": "#117 - Alert",
	"Halfling+Honest": "#107 - Lucky",
	"Halfling+Dishonest": "#107 - Lucky",
	
	"Small+Simple-minded": "#070 - Counterstrike",
	"Small+Streetsmart": "#089 - Reactive Shield",
	"Small+Booksmart": "#134 - Filibuster",
	"Small+Wise": "#067 - Endure",
	"Small+Military": "#087 - Bait and Switch",
	"Small+Criminal": "#106 - Lost in the Crowd",
	"Small+Noble": "#080 - Veil of Shadow",
	"Small+Craftsman": "#106 - Lost in the Crowd",
	"Small+Aggressive": "#120 - Mean Streak",
	"Small+Cautious": "#085 - Blur",
	"Small+Honest": "#073 - Muddle the Mind",
	"Small+Dishonest": "#120 - Mean Streak",
	
	"Big+Simple-minded": "#133 - Slow and Steady",
	"Big+Streetsmart": "#103 - Born Leader",
	"Big+Booksmart": "#091 - Wind Blast",
	"Big+Wise": "#103 - Born Leader",
	"Big+Military": "#124 - Command Respect",
	"Big+Criminal": "#101 - Die Hard",
	"Big+Noble": "#124 - Command Respect",
	"Big+Craftsman": "#088 - Calluses",
	"Big+Aggressive": "#079 - Fear",
	"Big+Cautious": "#095 - Switcheroo",
	"Big+Honest": "#062 - Taunt",
	"Big+Dishonest": "#095 - Switcheroo",
	
	"Nimble+Simple-minded": "#091 - Wind Blast",
	"Nimble+Streetsmart": "#070 - Counterstrike",
	"Nimble+Booksmart": "075 - Counterspell",
	"Nimble+Wise": "#075 - Counterspell",
	"Nimble+Military": "#066 - Protective Rush",
	"Nimble+Criminal": "#080 - Veil of Shadow",
	"Nimble+Noble": "#139 - Fine Touch",
	"Nimble+Craftsman": "#139 - Fine Touch",
	"Nimble+Aggressive": "#102 - Opportunist",
	"Nimble+Cautious": "#105 - Acrobatic Dodge",
	"Nimble+Honest": "#105 - Acrobatic Dodge",
	"Nimble+Dishonest": "#102 - Opportunist",
	
	"Stout+Simple-minded": "#133 - Slow and Steady",
	"Stout+Streetsmart": "#089 - Reactive Shield",
	"Stout+Booksmart": "#134 - Filibuster",
	"Stout+Wise": "#067 - Endure",
	"Stout+Military": "#065 - Square Off",
	"Stout+Criminal": "#101 - Die Hard",
	"Stout+Noble": "#065 - Square Off",
	"Stout+Craftsman": "#088 - Calluses",
	"Stout+Aggressive": "#140 - Gourmand",
	"Stout+Cautious": "#092 - Resistance",
	"Stout+Honest": "#092 - Resistance",
	"Stout+Dishonest": "#140 - Gourmand",
	
	"Simple-minded+Military": "#125 - Don't Overthink it!",
	"Simple-minded+Criminal": "#125 - Don't Overthink it!",
	"Simple-minded+Noble": "#072 - Disguise",
	"Simple-minded+Craftsman": "#082 - Sleep Powder",
	"Simple-minded+Aggressive": "#078 - What doesn't kill you",
	"Simple-minded+Cautious": "#109 - Pacifism",
	"Simple-minded+Honest": "#073 - Muddle the Mind",
	"Simple-minded+Dishonest": "#087 - Bait and Switch",
	
	"Streetsmart+Military": "#135 - Grand Strategy",
	"Streetsmart+Criminal": "#126 - Fast Talker",
	"Streetsmart+Noble": "#126 - Fast Talker",
	"Streetsmart+Craftsman": "#113 - Scavenging",
	"Streetsmart+Aggressive": "#086 - Quick Wit",
	"Streetsmart+Cautious": "#071 - Well-Scouted",
	"Streetsmart+Honest": "#131 - Disarming Smile",
	"Streetsmart+Dishonest": "#072 - Disguise",
	
	"Booksmart+Military": "#135 - Grand Strategy",
	"Booksmart+Criminal": "#084 - Assassin's Guide",
	"Booksmart+Noble": "#108 - Healing Word",
	"Booksmart+Craftsman": "#093 - Maelstrom",
	"Booksmart+Aggressive": "#086 - Quick Wit",
	"Booksmart+Cautious": "#071 - Well-Scouted",
	"Booksmart+Honest": "#079 - Fear",
	"Booksmart+Dishonest": "#110 - Scry",
	
	"Wise+Military": "#100 - Strategic Mind",
	"Wise+Criminal": "#100 - Strategic Mind",
	"Wise+Noble": "#108 - Healing Word",
	"Wise+Craftsman": "#114 - Alchemize",
	"Wise+Aggressive": "#081 - Tough Skin",
	"Wise+Cautious": "#109 - Pacifism",
	"Wise+Honest": "#131 - Disarming Smile",
	"Wise+Dishonest": "#110 - Scry",
	
	"Military+Aggressive": "#104 - Coordinated Assault",
	"Military+Cautious": "#113 - Scavenging",
	"Military+Honest": "#104 - Coordinated Assault",
	"Military+Dishonest": "#113 - Scavenging",
	
	"Criminal+Aggressive": "#084 - Assassin's Guide",
	"Criminal+Cautious": "#112 - Pickpocket",
	"Criminal+Honest": "#096 - Adaptible",
	"Criminal+Dishonest": "#112 - Pickpocket",
	
	"Noble+Aggressive": "#127 - It's a Deal!",
	"Noble+Cautious": "#068 - Barricade",
	"Noble+Honest": "#127 - It's a Deal",
	"Noble+Dishonest": "#062 - Taunt",
	
	"Craftsman+Aggressive": "#119 - Manipulate Trap",
	"Craftsman+Cautious": "#068 - Barricade",
	"Craftsman+Honest": "#096 - Adaptible",
	"Craftsman+Dishonest": "#119 - Manipulate Trap",
	

};
